# -*- coding: utf-8 -*-
"""BERTopic Model (Good for Scam/Null Sorting)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fd18qpF9bdi0I5t2Bll12ens6EJqGuID

# Set-Up
"""

# Installations:
# may be needed:
# !pip install --upgrade --force-reinstall bertopic sentence-transformers hdbscan numba numpy
!pip install bertopic sentence-transformers hdbscan numba numpy

# Imported Libraries:
import pandas as pd
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from hdbscan import HDBSCAN

# Import Contact Requests
df = pd.read_excel('/content/Contact Requests (Oct-Mar).xlsx')

df["COMMENTS"] = df["COMMENTS"].astype(str)
print(df["COMMENTS"])

"""# Topic Creation"""

# Create Topics
topic_model = BERTopic(embedding_model='all-mpnet-base-v2', hdbscan_model=HDBSCAN(min_cluster_size=15, min_samples=4))
topics, probs = topic_model.fit_transform(df["COMMENTS"])
df["topic"] = topics

# Determine counts of topic
df["topic"].value_counts()

# show df rows where topic is 1
df[df["topic"] == 3]

# Parameter Testing
topic_model = BERTopic(embedding_model='all-mpnet-base-v2', hdbscan_model=HDBSCAN(min_cluster_size=10, min_samples=2))
topics, probs = topic_model.fit_transform(df["COMMENTS"])
df["topic"] = topics

df['topic'].value_counts().plot(kind = 'bar')
